services:
  - type: web
    name: rails-api
    env: ruby
    rootDir: backend
    buildCommand: bundle install && bundle exec rails db:migrate
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: nuxt-frontend
    env: node
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: API_URL
        sync: false